CLOUDERA-BUILD: CDH-75151: HoS Hive smokes tests are failing with NoClassDefFoundError
Added spark-unsafe jar to CLASSPATH - required by recent change in Spark that introduced a new internal dependency on their end

Change-Id: If98c4589c6bc9a764c3f4f8ced60fa4f976f6cad